class ConfigParameters:
    """
    Configuration settings names
    """

    TABPY_PWD_FILE = "TABPY_PWD_FILE"
    TABPY_PORT = "TABPY_PORT"
    TABPY_QUERY_OBJECT_PATH = "TABPY_QUERY_OBJECT_PATH"
    TABPY_STATE_PATH = "TABPY_STATE_PATH"
    TABPY_TRANSFER_PROTOCOL = "TABPY_TRANSFER_PROTOCOL"
    TABPY_CERTIFICATE_FILE = "TABPY_CERTIFICATE_FILE"
    TABPY_KEY_FILE = "TABPY_KEY_FILE"
    TABPY_PWD_FILE = "TABPY_PWD_FILE"
    TABPY_LOG_DETAILS = "TABPY_LOG_DETAILS"
    TABPY_STATIC_PATH = "TABPY_STATIC_PATH"
    TABPY_MAX_REQUEST_SIZE_MB = "TABPY_MAX_REQUEST_SIZE_MB"
    TABPY_EVALUATE_TIMEOUT = "TABPY_EVALUATE_TIMEOUT"
