class SettingsParameters:
    '''
    Application (TabPyApp) settings names
    '''
    TransferProtocol = 'transfer_protocol'
    Port = 'port'
    ServerVersion = 'server_version'
    UploadDir = 'upload_dir'
    CertificateFile = 'certificate_file'
    KeyFile = 'key_file'
    StateFilePath = 'state_file_path'
    ApiVersions = 'versions'
    LogRequestContext = 'log_request_context'
    StaticPath = 'static_path'
    EvaluateTimeout = 'evaluate_timeout'
